int _putchar(char c);
int print_alphabet();
int print_alphabet_x10();
int _islower(int l);
int _isalpha(int l);
int print_sign(int l);
int _abs(int num);
int print_last_digit(int num);
void jack_bauer();
void times_table();
int add(int num1, int num2);
int print_to_98(int num);
void print_times_table(int n);
