int _putchar(char c);
int print_alphabet();
int print_alphabet_x10();
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int num1, int num2);
int print_to_98(int ns);
void print_times_table(int n);
